var OVERLAY_PRIORITY = /* @__PURE__ */ ((OVERLAY_PRIORITY2) => {
  OVERLAY_PRIORITY2[OVERLAY_PRIORITY2["MIN_PRIORITY"] = 0] = "MIN_PRIORITY";
  OVERLAY_PRIORITY2[OVERLAY_PRIORITY2["HEX_GRID"] = 1] = "HEX_GRID";
  OVERLAY_PRIORITY2[OVERLAY_PRIORITY2["CONTINENT_LENS"] = 2] = "CONTINENT_LENS";
  OVERLAY_PRIORITY2[OVERLAY_PRIORITY2["SETTLER_LENS"] = 3] = "SETTLER_LENS";
  OVERLAY_PRIORITY2[OVERLAY_PRIORITY2["PLOT_HIGHLIGHT"] = 4] = "PLOT_HIGHLIGHT";
  OVERLAY_PRIORITY2[OVERLAY_PRIORITY2["CULTURE_BORDER"] = 5] = "CULTURE_BORDER";
  OVERLAY_PRIORITY2[OVERLAY_PRIORITY2["UNIT_ABILITY_RADIUS"] = 6] = "UNIT_ABILITY_RADIUS";
  OVERLAY_PRIORITY2[OVERLAY_PRIORITY2["UNIT_MOVEMENT_SKIRT"] = 7] = "UNIT_MOVEMENT_SKIRT";
  OVERLAY_PRIORITY2[OVERLAY_PRIORITY2["CURSOR"] = 8] = "CURSOR";
  OVERLAY_PRIORITY2[OVERLAY_PRIORITY2["MAX_PRIORITY"] = 9] = "MAX_PRIORITY";
  return OVERLAY_PRIORITY2;
})(OVERLAY_PRIORITY || {});

export { OVERLAY_PRIORITY as O };
//# sourceMappingURL=utilities-overlay.chunk.js.map
